config/routes.rb
SampleApp::Application.routes.draw do

  get "campaigns/new"

  resources :roles

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :campaigns

  resources :prospects do
    member do
      get :assign
    end
  end

  
  resources :clients
 
    
  match '/prospects/testun',  :to => 'prospects#testun'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  
  root :to => 'pages#home'

end

app/models/prospect.rb
class Prospect < ActiveRecord::Base
  attr_accessible :last_name, :first_name, :civility, :birthyear,  :email, :address, :postal_code, :digital_code,
        :floor, :city, :phone_number, :office_phone_number, :mobile_phone_number, :situation_familiale, :nb_enfants_a_charges,  
        :professional_status, :revenus_mensuels_net, :logement_rp, :mensualite_rp, :impots_sur_le_revenu, :charges_rp, :charges_autres,
        :taux_endettement, :prospect_status, :rendezvous_at, :rendezvous_place, :to_recall, :to_recall_at, :hors_cible_cause, :comments, 
        :consultant_id, :off_target_cause, :timespent
  
  belongs_to :user
  
  belongs_to :campaign

  has_one :client, :dependent => :destroy

  #phonenumber_regex = /\A([0][0-9]([-. ]?[0-9]{2}){4,})?\z/i
  
  #datetime_regex = /(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[012])/((19|20)\\d\\d)/i

  validates :professional_status, :presence => true, :if => :rendezvous_status_selected?

  validates :impots_sur_le_revenu, :presence => true, :if => :rendezvous_status_selected?
  
  validates :last_name, :uniqueness => { :scope => [:first_name, :phone_number] | [:first_name, :office_phone_number] | [:first_name, :mobile_phone_number] },
                :length   => { :maximum => 32 }, :if => :rendezvous_status_selected?

  validates :first_name, :length   => { :maximum => 32 },
                :allow_nil => true, :allow_blank => true
                  
  validates :civility, :length => { :maximum => 3 }
  
  validates :birthyear, :numericality => { :less_than_or_equal_to => 120, :greater_than_or_equal_to => 18 },
                :allow_nil => true, :allow_blank => true, :presence => true, :if => :rendezvous_status_selected?
  
  validates :email, :email_format => true,
                :allow_nil => true, :allow_blank => true
  
  validates :address, :presence => true, :if => :rendezvous_status_selected?
  
  validates :postal_code, :numericality  => true, :length   => { :minimum => 4, :maximum => 5 },
                  :allow_nil => true, :allow_blank => true
                  
  validates :digital_code, :length   => { :minimum => 2, :maximum => 10 },
                :allow_nil => true, :allow_blank => true
                
  validates :floor, :numericality  => true,
                :allow_nil => true, :allow_blank => true
  
  validates :city,  :length   => { :maximum => 64 },
                :allow_nil => true, :allow_blank => true, :presence => true, :if => :rendezvous_status_selected?

  validates :phone_number, :uniqueness => { :scope => [:last_name, :first_name] }, :numericality  => true,
                :length => { :is => 10 }, :allow_nil => true, :allow_blank => true
                 #, :scope => :user_id pour avoir phone_number_1 & usier_id uniques
   
  validates :office_phone_number, :numericality  => true, :uniqueness => { :scope => [:last_name, :first_name] },
                :length => { :is => 10 }, :allow_nil => true, :allow_blank => true
                 #, :scope => :user_id pour avoir phone_number_1 & usier_id uniques

  validates :mobile_phone_number, :uniqueness => { :scope => [:last_name, :first_name] },
                :length => { :is => 10 }, :allow_nil => true, :allow_blank => true
  
  validates :nb_enfants, :numericality  => true,  :length   => { :maximum => 30 },
                :allow_nil => true, :allow_blank => true
  
  validates :nb_enfants_a_charges, :numericality  => true,  :length   => { :maximum => 30 },
                :allow_nil => true, :allow_blank => true
  
  validates :revenus_mensuels_net, :numericality  => true,  :length   => { :maximum => 30 },
                :allow_nil => true, :allow_blank => true
  
  validates :mensualite_rp, :numericality => true, :length => { :maximum => 8 },
                :allow_nil => true, :allow_blank => true
  
  validates :charges_rp, :numericality => true, :length => { :maximum => 8 },
                :allow_nil => true, :allow_blank => true
  
  validates :charges_autres, :numericality => true, :length => { :maximum => 8 },
                :allow_nil => true, :allow_blank => true
  
  validates :taux_endettement, :numericality => { :less_than_or_equal_to => 100 },
                :allow_nil => true, :allow_blank => true

  validates :prospect_status, :length => { :maximum => 32 }, :presence => true
  
  validates :rendezvous_at, :date => {:after => Time.now, :before => Time.now + 1.year},
                :allow_nil => true, :allow_blank => true, :presence => true, :if => :rendezvous_status_selected?
  
  validates :rendezvous_place, :length => { :maximum => 32 }, :presence => true, :if => :rendezvous_status_selected?
  
  validates :to_recall, :length => { :is => 10 }, :presence => true, :if => :to_recall_status_selected?
  
  validates :to_recall_at, :date  => { :after => Time.now, :before => Time.now + 1.year },
                :presence => true, :if => :to_recall_status_selected?
  
  validates :off_target_cause, :length => { :maximum => 32 }, :presence => true, :if => :off_target_selected?
  
  validates :user_id, :presence => true
  
  before_save :age_to_birthyear
  
  #searchable do
  #  text :last_name
  #  text :city, :boost => 5
  #  text :first_name
  #  text :postal_code
  #  text :prospect_status
  #  string :prospect_status
  #  string :last_name
  #  time :updated_at
  #Send
  
  def feed_on_connected_user
     Prospect.where("user_id = ?", id)
  end
 
  def self.search(search)
    if search
      where('last_name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
 
  def self.selected_status(prospect_status)
    if prospect_status
      where('prospect_status = ?', "#{prospect_status.humanize}")
    else
      scoped
    end
  end
  
  def age_to_birthyear
    if !self.birthyear.nil?
      self.birthyear = Time.now.year - self.birthyear
    end
  end
  
  private
  
  def to_recall_status_selected?
    self.prospect_status == "A rappeler"
  end
  
  def off_target_selected?
    self.prospect_status == "Hors cible"
  end
  
  def rendezvous_status_selected?
    self.prospect_status == "Rendez-vous"
  end
end

app/controllers/prospects_controller.rb
#Encoding: UTF-8
class ProspectsController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]

  load_and_authorize_resource
  
  include ProspectsHelper   
  
  helper_method :sort_column, :sort_direction

  def index
    @title = "Tous les prospects" 

    @status = params[:prospect_status]
    
    #@search = Prospect.search do
     # fulltext params[:search]
    @prospects =  Prospect.search(params[:s])

       # with :prospect_status, params[:prospect_status].humanize
       @prospects = @prospects.selected_status(params[:prospect_status])
      if  !params[:min_date].to_s.empty?
        # with(:updated_at).greater_than(params[:min_updated_date])
        @prospects = @prospects.where("updated_at >= ?",Time.parse(params[:min_date]))  
      end
      if !params[:max_date].to_s.empty?
       #with(:updated_at).less_than(params[:max_updated_date])
       @prospects = @prospects.where("updated_at <= ?",Time.parse(params[:max_date]))  
      end
     # order_by sort_column, sort_direction
    #end
    #@prospects = @search.results
    @prospects = @prospects.order(sort_column + " " + sort_direction)
    @prospects = @prospects.paginate(:per_page => 5, :page => params[:page]) 
  end
  
  def show
    if !@prospect.birthyear.nil?
      @prospect.birthyear = Time.now.year - @prospect.birthyear 
    end
    @title = @prospect.first_name + " " + @prospect.last_name
    
    respond_to do |format|
      format.html
      format.pdf { 
        html = render_to_string :action => "prospection_slip.html.erb"
        kit  = PDFKit.new(html)
        kit.stylesheets << File.join( RAILS_ROOT, "public", "stylesheets", "pdf.css" )
 
        send_data kit.to_pdf, :filename => "item.pdf", :type => 'application/pdf', :disposition => 'inline'
      }
    end
  end
  
  def new
     @title = "Création d'un prospect"
     @prospect.timespent = "00:00:00"
  end
  
  def create
    @prospect.user  = current_user
    if @prospect.save
      flash[:success] = "Prospect created!"
      if @prospect.prospect_status == "to_classify"
          @client = Client.new
          @client.prospect_id = @prospect.id
          @client.save
      end
      redirect_to root_path
    else
      @title = "Création d'un prospect"
      render 'new'
    end
  end
  
  def edit
    @titre = "Édition du prospect"
    @prospect.birthyear = get_age @prospect.birthyear
    @prospect.timespent = @prospect.timespent.strftime('%H:%M:%S')
  end

  def update
    if @prospect.update_attributes(params[:prospect])
      flash[:success] = "Prospect actualisé."

      @client = Client.where("prospect_id = ?", @prospect.id)
      
      if @prospect.prospect_status == "To classify" && @client.empty?
          @client = Client.new  
          @client.prospect_id = @prospect.id
          @client.save
      end
      redirect_to @prospect
    else
      @title = "Édition du prospect"
      render 'edit'
    end
  end
  
  def assign
    @prospect = Prospect.find(params[:id])
    @users = User.all
    @title = "Assignation du Prospect"
  end
  
  def destroy
    @prospect.destroy    
    redirect_to prospects_path
  end
  
  private
  
  def sort_column
    Prospect.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:dir]) ? params[:dir] : "desc"
  end  
end

app/helpers/prospects_helper.rb
module ProspectsHelper

  def get_age(birth_year)
    if !birth_year.nil?
      birth_year= (Time.now.year - birth_year )
    end
    return birth_year  
  end

end

app/views/prospects/_prospect.html.erb
<%= hidden_field_tag :prospect_status, params[:prospect_status] %>
<%= hidden_field_tag :dir, params[:dir] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= hidden_field_tag :min_date, params[:min_date] %>
<%= hidden_field_tag :max_date, params[:max_date] %>
<table class="order_by">
  <td>
    <%= sortable "last_name", "Tri par nom" %>
  </td>
  <td>
    <%= sortable "updated_at", "Tri par date" %>
  </td>
</table>
<%= will_paginate %>
<table class="prospects" summary="User prospects">
 <thead>
  <tr>
   <th>Nom</th>
   <th>Statut</th>
   <th>Téléphone</th>
   <th>Prospecteur</th>
   <th>Date de saisie</th>
   <th>Modifications</th>
  </tr>
 </thead>
 <tbody>
<% for prospect in @prospects %>
<% if can? :read, prospect %>

    <tr>
      <td>
        <% if prospect.last_name? %>
        <%= link_to prospect.last_name, prospect %>
        <% else %>
        None
        <% end %>
      </td>
      <td>
        <% if prospect.prospect_status? %>
        <%= prospect.prospect_status%>
        <% else %>
        None
        <% end %>
      </td>  
      <td>
        <% if prospect.office_phone_number? %>
        <%= prospect.office_phone_number%>
        <% else %>
        None
        <% end %>
      </td>  
      <td>
        <%= prospect.user.firstname + " "+ prospect.user.lastname %>
      </td>
      <td>
        <%= prospect.updated_at.strftime("%e %b %Y %H:%M") %>
      </td>
      <td>
        <% if can? :update, prospect %>  
          <%= link_to "éditer", edit_prospect_path(prospect) %>
        <% end %>
        <% if can? :destroy, prospect %>
          <%= link_to "supprimer", prospect, :method => :delete,
                                     :confirm => "Etes-vous certain de vouloir supprimer " + prospect.first_name + " " + prospect.last_name + " ?" %>
        <%  end %>
        <% if can? :assign, prospect %>
          <%= link_to "assigner", assign_prospect_path(prospect) %>
        <%  end %>
      </td>
    </tr>
    <%  end %>
    <% end %>
 </tbody>
</table>
<%= will_paginate %>

app/views/prospects/assign.html.erb
  <table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= @title %>
      </h1>
      <%= form_for(@prospect, :validate=>true) do |f| %>
      <%= render 'shared/error_messages', :object => f.object %>     
      <strong>Nom</strong> <%= @prospect.last_name%><br />
      <strong>Prénom</strong> <%= @prospect.first_name %><br />
      <strong>EMail</strong> <%= @prospect.email %><br />
      <strong>Adresse</strong> <%= @prospect.address %><br />
      <strong>Age</strong> <%= @prospect.birthyear %><br />
      <strong>Statut du prospect</strong> <%= @prospect.prospect_status %>
      <strong>Consultant assigné: </strong><br />
      <%=  f.select :consultant_id, @users.map { |u| ["#{u.firstname} #{u.lastname}", u.id] },:selected => @prospect.consultant_id, :include_blank => true %>
      <div class="actions">
        <%= f.submit "Update" %>
      </div>  
    <% end %>
    </td>
  </tr>
</table>

app/views/prospects/edit.html.erb
<h1><%= @title %></h1>
<%= form_for(@prospect, :validate=>true) do |f| %>
<div id="rightCol" class="validate_box">
    <div id="bardivs">
      <div id="progressbar"></div>
      <div id="progresstext"></div>
    </div>
    <div class="timespent">
    <%= f.text_field :timespent %>
  </div>  
    <div class="field_radio">
      <%= f.radio_button :prospect_status, "Rendez-vous" %>RDV OK<br />
    </div>
    <div class="field_radio">
      <%= f.radio_button :prospect_status, "A rappeler" %>A rappeler<br />
      <p id="prospect_prospect_status_a_rappeler" class="hidden_fields">
        <%= f.label :to_recall %><br />
        <%= f.text_field :to_recall, :value => @prospect.to_recall %><br />
        <%= f.label :to_recall_at %><br />
        <%= f.text_field :to_recall_at, :value => @prospect.to_recall_at.try(:strftime,"%d/%m/%Y %H:%M"), :class => "datepicker_edit" %>
      </p>
    </div>
    <div class="field_radio">
      <%= f.radio_button :prospect_status, "Hors cible" %>Hors Cible<br />
      <p id="prospect_prospect_status_hors_cible" class="hidden_fields">
        <%= f.label :off_target_cause %><br />
        <%= f.select :off_target_cause, options_for_select([["Hors impôts", "Hors impôts"], "Hors âge", "Hors origine"]) %>
      </p>
    </div>
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
</div>
<div id="contentArea">  
  <%= render 'shared/error_messages', :object => f.object %>
  <div id="prospect_fieldset">
  <fieldset>
    <legend>1ère étape: Question d'introduction</legend>
  <div class="field_first">
    <%= f.label :professional_status, "Statut professionnel:"  %>
    <%= f.radio_button :professional_status, "Cadre" %>Cadre
    <%= f.radio_button :professional_status, "Non cadre" %>Non cadre
  </div>
  <div class="field_first">
    <%= f.label :impots_sur_le_revenu, "Impot sur le revenu:"  %>
    <%= f.radio_button :impots_sur_le_revenu, "-3500€" %>-3500€
    <%= f.radio_button :impots_sur_le_revenu, "+3500€" %>+3500€
  </div>
  </fieldset>
  <fieldset id="prospect_fieldset">
    <legend>2ème étape: Prise de rendez-vous</legend>
    <div class="field">
      <%= f.label :rendezvous_at %>
      <%= f.text_field :rendezvous_at, :class => "datepicker_index", :onchange => "$('input[id=prospect_rendezvous_at]').val(this.value)" %>
    </div>
    <div class="field_radio" >
    <%= f.label :rendezvous_place, "Lieu de réunion"  %>
    <%= f.radio_button :rendezvous_place, "Professionnel", :onclick => "$('input').each(function(){
        switch(this.id){
          case 'prospect_address': $(this).val(''); break;
          case 'prospect_postal_code': $(this).val(''); break;
          case 'prospect_city': $(this).val(''); break;
          case 'prospect_floor': $(this).val(''); break;
          case 'prospect_digital_code': $(this).val(''); break;
            $(this).val('');
        }
    });" %> Lieu professionnel

    <%= f.radio_button :rendezvous_place, "Domicile", :onclick => "$('input').each(function(){
        switch(this.id){
          case 'prospect_address': $(this).val(''); break;
          case 'prospect_postal_code': $(this).val(''); break;
          case 'prospect_city': $(this).val(''); break;
          case 'prospect_floor': $(this).val(''); break;
          case 'prospect_digital_code': $(this).val(''); break;
            $(this).val('');
        }
    });" %> Domicile
    <%= f.radio_button :rendezvous_place, "Cabinet", :onclick => "$('input').each(function(){
        switch(this.id){
          case 'prospect_address': $(this).val('192 rue Lauriston'); break;
          case 'prospect_postal_code': $(this).val('75016'); break;
          case 'prospect_city': $(this).val('Paris'); break;
          case 'prospect_floor': $(this).val(''); break;
          case 'prospect_digital_code': $(this).val(''); break;
            $(this).val('');
        }
    });" %> Cabinet
  </div>
    <div class="field_first">
      <%= f.label :address %>
      <%= f.text_field :address, options={:style=>"width:430px"} %>
    </div>
    <div class="field_second">
      <%= f.label :postal_code %>
      <%= f.text_field :postal_code %>
    </div>
    <div class="field_second">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div class="field_second">
      <%= f.label :digital_code %>
      <%= f.text_field :digital_code %>
    </div>
    <div class="field_second"> 
      <%= f.label :floor %>
      <%= f.text_field :floor %>
    </div>
    <div class="field_first">
      <%= f.label :comments %>
      <%= f.text_area :comments %>
  </div>
    <div class="field_second">
      <%= f.label :office_phone_number %>
      <%= f.text_field :office_phone_number %>
    </div>
      <div class="field_second">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number %>
      </div>
    <div class="field_first">
      <%= f.label :mobile_phone_number %>
      <%= f.text_field :mobile_phone_number %>
    </div>
  </fieldset>
  <fieldset id="prospect_fieldset">
    <legend>3ème étape: Qualifications</legend>
  <div class="field_first">
    <%= f.label :civility, "Civilité"  %>
    <%= f.radio_button :civility, "M." %>M.
    <%= f.radio_button :civility, "Mlle" %>Melle
    <%= f.radio_button :civility, "Mme" %>Mme
  </div>
  <div class="field_second">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field_second">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
   <div class="field_first">
    <%= f.label :birthyear %>
    <%= f.text_field :birthyear %>
  </div>
  <div class="field_second">
    <%= f.label :situation_familiale %>
    <%= f.text_field :situation_familiale %>
  </div>
  <div class="field_second">
    <%= f.label :nb_enfants_a_charges %>
    <%= f.text_field :nb_enfants_a_charges %>
  </div>
  <div class="field_first">
    <%= f.label :charges_rp %>
    <%= f.text_field :charges_rp %>
  </div>
  <div class="field_second">
    <%= f.label :revenus_mensuels_net %>
    <%= f.text_field :revenus_mensuels_net %>
  </div>
  <div class="field_second">
    <%= f.label :taux_endettement  %>
    <%= f.text_field :taux_endettement  %>
  </div>
  </fieldset>
  </div>
</div>
  
<% end %>

app/views/prospects/edit_old.html.erb
<h1>Edition du prospect</h1>
<%= form_for(@prospect, :validate=>true) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="timespent">
    <%= f.text_field :timespent %>
  </div>  
  <fieldset>
    <legend>1ère étape: Question d'introduction</legend>
  <div class="checkbox">
    <%= f.label :professional_status, "Statut professionnel:"  %>
    <%= f.radio_button :professional_status, "Cadre" %>Cadre
    <%= f.radio_button :professional_status, "Non cadre" %>Non cadre
  </div>
  <div class="checkbox">
    <%= f.label :impots_sur_le_revenu, "Impot sur le revenu:"  %>
    <%= f.radio_button :impots_sur_le_revenu, "-3500€" %>-3500€
    <%= f.radio_button :impots_sur_le_revenu, "+3500€" %>+3500€
  </div>
  </fieldset>
  <fieldset>
    <legend>2ème étape: Prise de rendez-vous</legend>
  <div class="checkbox">
    <%= f.label :rendezvous_at, "Impot sur le revenu:"  %>
    <%= f.radio_button :rendezvous_at, "Lieu professionnel" %>Lieu professionnel
    <%= f.radio_button :rendezvous_at, "Cabinet" %>Cabinet
    <%= f.radio_button :rendezvous_at, "Domicile" %>Domicile
  </div>
    <div class="field">
      <%= f.label :rendezvous_at %>
      <%= f.text_field :rendezvous_at %>
    </div>
    <div class="field">
      <%= f.label :rendezvous_place %>
      <%= f.text_field :rendezvous_place %>
    </div>
    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :postal_code %>
      <%= f.text_field :postal_code %>
    </div>
    <div class="field">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div class="field">
      <%= f.label :floor %>
      <%= f.text_field :floor %>
    </div>
    <div class="field">
      <%= f.label :digital_code %>
      <%= f.text_field :digital_code %>
    </div>
    <div class="field">
      <%= f.label :comments %>
      <%= f.text_area :comments %>
    </div>
    <div>
      <div class="field">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number %>
      </div>
      <div class="field">
        <%= f.label :office_phone_number %>
        <%= f.text_field :office_phone_number %>
      </div>
    </div>
    <div class="field">
      <%= f.label :mobile_phone_number %>
      <%= f.text_field :mobile_phone_number %>
    </div>
  </fieldset>
  <fieldset>
    <legend>3ème étape: Qualifications</legend>
  <div class="checkbox">
    <%= f.label :civility, "Civilité"  %>
    <%= f.radio_button :civility, "M." %>M.
    <%= f.radio_button :civility, "Mlle" %>Melle
    <%= f.radio_button :civility, "Mme" %>Mme
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
   <div class="field">
    <%= f.label :birthyear %>
    <%= f.text_field :birthyear %>
  </div>
  <div class="field">
    <%= f.label :situation_familiale %>
    <%= f.text_field :situation_familiale %>
  </div>
  <div class="field">
    <%= f.label :nb_enfants_a_charges %>
    <%= f.text_field :nb_enfants_a_charges %>
  </div>
  <div class="field">
    <%= f.label :revenus_mensuels_net %>
    <%= f.text_field :revenus_mensuels_net %>
  </div>
  <div class="field">
    <%= f.label :charges_rp %>
    <%= f.text_field :charges_rp %>
  </div>
  <div class="field">
    <%= f.label :birthyear %>
    <%= f.text_field :birthyear %>
  </div>
  <div class="field">
    <%= f.label :taux_endettement  %>
    <%= f.text_field :taux_endettement  %>
  </div>
  </fieldset>
  <div id="validate_box">
    <div class="field">
      <%= f.radio_button :prospect_status, "To classify" %>RDV OK<br />
      <p id="prospect_prospect_status_rendezvous_booked" class="hidden_fields">
        <%= f.label :rendezvous_at %>
         <%= f.text_field :rendezvous_at, :value => @prospect.rendezvous_at.try(:strftime,"%d/%m/%Y %H:%M"), :class => "datepicker_edit" %>
      </p>
    </div>
    <div class="field">
      <%= f.radio_button :prospect_status, "To recall" %>A rappeler<br />
      <p id="prospect_prospect_status_to_recall" class="hidden_fields">
        <%= f.label :to_recall %><br />
        <%= f.text_field :to_recall, :value => @prospect.to_recall %><br />
        <%= f.label :to_recall_at %><br />
        <%= f.text_field :to_recall_at, :value => @prospect.to_recall_at.try(:strftime,"%d/%m/%Y %H:%M"), :class => "datepicker_edit" %>
      </p>
    </div>
    <div class="field">
      <%= f.radio_button :prospect_status, "Off target" %>Hors Cible<br />
      <p id="prospect_prospect_status_off_target" class="hidden_fields">
        <%= f.label :off_target_cause %><br />
        <%= f.text_area :off_target_cause %>
      </p>
    </div>
    <div class="actions">
      <%= f.submit "Update" %>
    </div>
  </div>
<% end %>

app/views/prospects/index.html.erb
<h1>Tous les prospects</h1>

<%= link_to "Nouveau Prospect", new_prospect_path %><br/>

<div id="rightCol">
  <ul class="prospects_status">
    <li
      <% if @status.nil? %>
      class="selected"
      <% end %>
    >
      <%= link_to "Tous", prospects_path %>
    </li>
    <li
      <% if @status == "a_rappeler" %>
      class="selected"
      <% end %>  
    >
      <%= link_to "A rappeler", prospects_path(:prospect_status => "a_rappeler") %>
    </li>
    <li
      <% if @status == "rendez-vous" %>
      class="selected"
      <% end %>  
    >
      <%= link_to "RDV OK", prospects_path(:prospect_status => "rendez-vous") %>
    </li>
    <li
      <% if @status == "hors_cible" %>
      class="selected"
      <% end %>  
    >
      <%= link_to "Hors cible", prospects_path(:prospect_status => "hors_cible") %>
    </li>
  </ul>
  <div id="DateSearch">
  <%= form_tag prospects_path, :method => 'get', :id => "prospects_date_range" do %>
    <p>
      <% if !params[:prospect_status].nil? %>  
        <%= hidden_field_tag :prospect_status, params[:prospect_status] %>
      <% end %>
      <% if !params[:dir].nil? %>  
        <%= hidden_field_tag :dir, params[:dir] %>
      <% end %>
      <% if !params[:sort].nil? %>  
        <%= hidden_field_tag :sort, params[:sort] %>
      <% end %>
      <% if !params[:s].nil? %>    
        <%= hidden_field_tag :search, params[:s] %>
      <%  end %>
    <div>
      <label>Du:</label> <%= text_field_tag  :min_date, params[:min_date], :class => "datepicker_index" %>
    </div>
    <div>
      <label>Au: </label> <%= text_field_tag :max_date, params[:max_date], :class => "datepicker_index" %>     
    </div>
    </p>
    <div style="text-align: center;">
      <%= submit_tag "Rechercher période", :name => nil %>
    </div>
      <%= text_field_tag :s, params[:s] %>
      <%= submit_tag "Search", :name => nil %>
  </div>
  <% end %>
</div>
<div id="contentArea">


<%= form_tag prospects_path, :method => 'get', :id => "prospects_search" do %>
 <div id="prospects_found"><%= render 'prospect' %></div>

<% end %>
 </div>

app/views/prospects/index.js.erb
$("#prospects_found").html("<%= escape_javascript(render("prospect")) %>") 