config/routes.rb
SampleApp::Application.routes.draw do

  get "campaigns/new"

  resources :roles

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :campaigns

  resources :prospects do
    member do
      get :assign
    end
  end

  
  resources :clients
 
    
  match '/prospects/testun',  :to => 'prospects#testun'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  
  root :to => 'pages#home'

end

app/models/campaign.rb
#Encoding: UTF-8
class Campaign < ActiveRecord::Base

  attr_accessible :name, :campaign_type, :description, :first_phone_number, :last_phone_number
  
  belongs_to :user
  
  has_many :prospects
  
  validates :name, :length   => { :maximum => 32 },
              :presence => true, :uniqueness => true
            
  validates :campaign_type, :presence => true
  
  validates :first_phone_number, :length => { :is => 10 }, :presence => true, :if => :campaign_is_company?,
                 :allow_nil => true, :allow_blank => true
  
  validates :last_phone_number, :length => { :is => 10 }, :if => :campaign_is_company?,
                :allow_nil => true, :allow_blank => true

  def feed_on_connected_user
     Campaign.where("user_id = ?", id)
  end
 
  def self.selected_type(campaign_type)
    if campaign_type
      where('campaign_type = ?', "#{campaign_type}")
    else
      scoped
    end
  end
  
  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
 
  private
  
  def campaign_is_company?
    self.campaign_type == "Décline"
  end
  
end

app/controllers/campaigns_controller.rb
#Encoding: UTF-8
class CampaignsController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]

  load_and_authorize_resource
    
  helper_method :sort_column, :sort_direction
  
  def index
    @title = "Toutes les campagnes" 

    #@search = Prospect.search do
     # fulltext params[:search]
    @campaigns =  Campaign.search(params[:s])

       # with :prospect_status, params[:prospect_status].humanize
       @campaigns = @campaigns.selected_type(params[:type])
      if  !params[:min_date].to_s.empty?
        # with(:updated_at).greater_than(params[:min_updated_date])
        @campaigns = @campaigns.where("updated_at >= ?",Time.parse(params[:min_date]))  
      end
      if !params[:max_date].to_s.empty?
       #with(:updated_at).less_than(params[:max_updated_date])
       @campaigns = @campaigns.where("updated_at <= ?",Time.parse(params[:max_date]))  
      end
     # order_by sort_column, sort_direction
    #end
    #@prospects = @search.results
    @campaigns = @campaigns.order(sort_column + " " + sort_direction)
    @campaigns = @campaigns.paginate(:per_page => 5, :page => params[:page]) 
  end
  
  def show
    @title = "Campagne: "+@campaign.name
  end
  
  def new
     @title = "Création d'une campagne"
  end
 
  def create
    @campaign.user  = current_user
    if @campaign.save
      flash[:success] = "Campaign created!"
      redirect_to root_path
    else
      @title = "Création d'une campagne"
      render 'new'
    end
  end
  
  def destroy
    @campaign.destroy
    respond_to do |format|  
      format.html { redirect_to(campaigns_path) }  
      format.js
    end
  end

  private
  
  def sort_column
    Campaign.column_names.include?(params[:sort]) ? params[:sort] : "updated_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:dir]) ? params[:dir] : "desc"
  end  
  
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaign/_campaign.html.erb
<tr>
  <td class="prospect">
    <% if campaign.created_at == campaign.updated_at %>
      <span class="name">
        La campagne <%= link_to campaign.name %> a été créée.
      </span>
      <span class="timestamp">
        Posté: <%= time_ago_in_words(campaign.created_at) %>.
      </span>
    <% else %>
      <span class="name">
        La campagne <%= link_to campaign.name %> a été modifiée.
      </span>
    <% end %>
      <span class="timestamp">
        Posté: <%= time_ago_in_words(campaign.updated_at) %>.
      </span>
  </td>
  <td>
    <%= if can? :update, @campaign  %>
    <%= link_to "éditer", edit_campaign_path(campaign) %>
    <%= end %>
  </td>
  <td>
    <%= if can? :destroy, @campaign %>
    <%= link_to "supprimer", campaign, :method => :delete,
                                :confirm => "Etes-vous certain ?",
                                :title => campaign.name,
                                :remote=>true, :class=>'delete_prospect' %>
    <%= end %>
  </td>
  <% end %>
</tr>

app/views/campaign/destroy.js.erb
jQuery(function($) {

$('.delete_campaign').bind('ajax:success', 
  function() {
    $(this).closest('tr').fadeOut();
  }
 );
});

app/views/campaign/edit.html.erb
<h1>Edition du client</h1>

<%= nested_form_for @client, :html=>{:multipart => true } do |f| %>
<%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :string1 %><br />
    <%= f.text_field :string1 %>
  </div>
  <div class="field">
    <%= f.label :integer1 %><br/>
    <%= f.text_field :integer1 %>
  </div>
  <%= f.fields_for :attachments do |attachment_form|  %>
    <p>
    <%= attachment_form.label :description %><br />
    <%= attachment_form.text_area :description %>
    </p>
    <p>
      <%= image_tag(attachment_form.object.file.url) if attachment_form.object.file? %>

    <%= attachment_form.label :file %><br />
    <%= attachment_form.file_field :file %>
    </p>
    <%= attachment_form.link_to_remove "Remove this attachment" %>
  <% end %>
  <%= f.link_to_add "Add attachment", :attachments %>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

app/views/campaign/index.html.erb
<h1>Toutes les campagnes</h1>

<%= link_to "Nouvelle Campagne", new_campaign_path %><br/>

<%= will_paginate %>

<table class="prospects" summary="Campaigns">
  <%= render @campaigns %>    
</table>

<%= will_paginate %>

app/views/campaign/new.html.erb
#Encoding: UTF-8
<h1><%= @title %></h1>
<%= form_for(@campaign, :validate=>true) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name, "Intitulé:" %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :campaign_type, "Statut professionnel:"  %>
    <%= f.select :campaign_type, options_for_select([["Décline", "Décline"], "Annuaire d'école", "Annuaire d'entreprise"]) %>
  </div>
  <div class="field">
    <%= f.label :first_phone_number, "Premier numéro de téléphone:"  %>
    <%= f.text_field :first_phone_number %>
  </div>
  <div class="field">
    <%= f.label :last_phone_number, "Dernier numéro de téléphone:"  %>
    <%= f.text_field :last_phone_number %>
  </div>
  <div class="actions">
    <%= f.submit "Soumettre" %>
  </div>
<% end %>

app/views/campaign/show.html.erb
<table class="campaign" summary="Information campagne">
  <tr>
    <td class="main">
      <h1>
        Campagne : <%= @title %>, créée le <%=  @created_at %> 
      </h1>
      <strong>Intitulé</strong> <%= @campaign.name %><br />
      <strong>Description</strong> <%= @campaign.description %><br />
      <% if @prospects.first_phone_number? %>  
      <strong>Premier numéro de téléphone</strong> <%= @prospect.first_phone_number %><br />
      <strong>Dernier numéro de téléphone</strong> <%= @prospect.last_phone_number %><br />     
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Informations sur cette campagne</strong><br/>
      <strong>Créée le</strong> <%= @prospect.created_at %><br/>
      <strong>Statut du prospect</strong> <%= @campaign.prospects.count %>
    </td>
  </tr>
</table>