config/routes.rb
SampleApp::Application.routes.draw do

  get "campaigns/new"

  resources :roles

  get "sessions/new"

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :microposts, :only => [:create, :destroy]
  resources :campaigns

  resources :prospects do
    member do
      get :assign
    end
  end

  
  resources :clients
 
    
  match '/prospects/testun',  :to => 'prospects#testun'
  
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  
  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "À Propos", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Tutoriel Rails</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Accueil", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Utilisateurs", users_path %></li>
      <li><%= link_to "Profil", current_user %></li>
      <% if can? :read, Campaign %>  
      <li><%= link_to "Campagnes", campaigns_path %></li>
      <% end %>
      <li><%= link_to "Prospects", prospects_path %></li>
      <li><%= link_to "Clients", clients_path %></li>
      <li><%= link_to "Réglages", edit_user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Aide", help_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Déconnexion", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "S'identifier", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults, "nested_form", "rails.validations", "rails.validations.custom" %>
       <title><%= title %></title>
    <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css" %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" %>
    <%= javascript_include_tag "jquery-ui-timepicker-addon" %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <div id="content">
        <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      <%= render 'layouts/footer' %>
      </div>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>